import React from 'react';
import { Link } from 'react-router-dom';
import { useNavigate } from 'react-router-dom';
import { useDispatch } from 'react-redux';
// import { reset } from '../../../features/admin/adminSlice';
import { adminLogout } from '../../../Store/user/userSlice';
import IconUsers from '../../icons/Users';
import IconHome from '../../icons/HomeIcon';
import IconPicture from '../../icons/PostIcon';
import IconLogout from '../../icons/LogoutIcon';